# Generated by Django 5.1.3 on 2024-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes', verbose_name='Cloth'),
        ),
    ]
